services:
  - type: web
    name: Digicraft API Processor
    env: node
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: node ./index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3030
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
