GET http://localhost:3030/api/rsvp

###

GET http://localhost:3030/wish

###

POST http://localhost:3030/api/inquiry
Content-Type: application/json

{
    "name": "Raed",
    "email": "Ya",
    "phoneNumber": "0172727305",
    "subject": "Kawan pengantin",
    "description": "3"
}

###

POST http://localhost:3030/rsvp

{
    "name": "Sulayman A",
    "message": "Wishing you a long and happy marriage."
}