GET http://localhost:3030/rsvp

###

POST http://localhost:3030/rsvp
Content-Type: application/json

{
    "name": "Raed Gibran",
    "isAttending": "Ya",
    "phoneNumber": "0172727305",
    "guestType": "Kawan pengantin",
    "paxCount": "3",
    "timeSlot": "12pm"
}

###

POST http://localhost:3030/ucapan

{
    "name": "Fifi",
    "ucapan": "Selamat pengantin baru."
}