GET http://localhost:3030/api/rsvp

###

GET http://localhost:3030/wish

###

POST http://localhost:3030/api/rsvp
Content-Type: application/json

{
    "name": "Raed Gibran",
    "isAttending": "Ya",
    "phoneNumber": "0172727305",
    "guestType": "Kawan pengantin",
    "paxCount": "3",
    "timeSlot": "12pm"
}

###

POST http://localhost:3030/rsvp

{
    "name": "Sulayman A",
    "message": "Wishing you a long and happy marriage."
}